live_config_reload = true

[window]
# Window decorations
#
# *Full*
# Borders and title bar
# *None*
# Neither borders nor title bar
# *Transparent* _(macOS only)_
# Title bar, transparent background and title bar buttons
# *Buttonless* _(macOS only)_
# Title bar, transparent background and no title bar buttons
#
# Default: _"Full"_
decorations = "Full"
# Background opacity as a floating point number from _0.0_ to _1.0_. The value
# \_0.0_ is completely transparent and _1.0_ is opaque.
#
# Default: _1.0_
opacity = 1.0
# startup_mode "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
# Startup mode (changes require restart)
#
# Default: _"Windowed"_
startup_mode = "Windowed"
# decorations_theme_variant "Dark" | "Light" | "None"
#
# Override the variant of the System theme/GTK theme/Wayland client side
# decorations. Set this to _"None"_ to use the system's default theme variant.
#
# Default: _"None"_
decorations_theme_variant = "None"

[window.dimensions]
columns = 100
lines = 30

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.primary]
background = "0x222436"
foreground = "0xc8d3f5"

[colors.bright]
black = '0x444a73'
red = '0xff757f'
green = '0xc3e88d'
yellow = '0xffc777'
blue = '0x82aaff'
magenta = '0xc099ff'
cyan = '0x86e1fc'
white = '0xc8d3f5'

[colors.normal]
black = '0x1b1d2b'
red = '0xff757f'
green = '0xc3e88d'
yellow = '0xffc777'
blue = '0x82aaff'
magenta = '0xc099ff'
cyan = '0x86e1fc'
white = '0x828bb8'

[[colors.indexed_colors]]
index = 16
color = '0xff966c'

[[colors.indexed_colors]]
index = 17
color = '0xc53b53'

[font]
builtin_box_drawing = false

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "F11"
mods = "Control|Shift"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "t"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "q"
mods = "Control|Shift"
mode = "~Alt"
action = "Quit"
