[project]
name = "nvim_utils"
version = "0.1.0"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["./rplugin/python3/utils"]

[tool.setuptools.package-dir]
"" = "./rplugin/python3/utils"

[tool.pyright]
venv = "nvim"
