# base config
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd no_beep extendedglob nomatch

# completion config
autoload -U compinit; compinit
zstyle ':completion:*' completer _extensions _complete _approximate
# zstyle ':completion:*' use-cache on
# zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"
zstyle ':completion:*:*:*:*:descriptions' format '%F{blue}-- %d --%f'
zstyle ':completion:*:*:*:*:corrections' format '%F{yellow}!- %d (errors: %e) -!%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*' file-list all
zstyle ':completion:*' file-sort change reverse
zstyle ':completion:*' complete-options true
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# bind key
bindkey -v
bindkey '^[[Z' reverse-menu-complete

# alias
alias ls="ls -lh --color=auto"
alias codeshot="silicon --from-clipboard --to-clipboard"
